spring:
  data:
    mongodb:
      uri: mongodb+srv://abdulnafayworks:27BR2FVbZy1w5efw@cluster0.cb3cfue.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true